### ISSUE TITLE
:where() :is() — A New CSS(新CSS - :where() :is())

### ISSUE THREAD

**Issue by bt2ee** [sqshada/Translation-day#14]
### 原文地址

https://roilivne14.medium.com/where-is-a-new-css-8cee1141a5f3

### 翻译

> If you haven’t heard about the :where() and :is() pseudo-classes,
don’t feel bad. They were only recently introduced to most browsers.
But they just might be your new favorite thing in vanilla CSS!
In this article, we will learn how to use our new handy tools in writing CSS.

如果你没有听说 `:where()` 和 `:is()` 伪类，不要难过。它们也是不久前才引入大多数浏览器的。但是它们可能是你在 香草CSS 中最喜欢的东西！
在这篇文章中，我们将会学习如何使用我们好用的新工具编写 CSS。

> #### :is()

#### :is()

> Think about when you want to apply the same styling to multiple elements in your HTML. You’d probably end up with something that looks like this:

思考一下当你想要在你的 HTML 中多处元素使用相同样式。你可能会写成这样：

```css
.main h1,
.main h2,
.main .heading, {
  line-height: 1.2;
}
.nav li,
.nav p {
  padding: 5px 10px;
}
```

> With `:is()` we can write our CSS in a shorter, quicker, and more elegant way.

使用 `:is()` 我们可以更短更快更优雅的编写我们的 CSS。

```css
.main :is(h1, h2, .heading){
  line-height: 1.2;
}
.nav :is(li, p) {
  padding: 5px 10px;
}
```

> Imagine all the many lines you’re saving!
> This is very similar to how nesting works with preprocessors such as SCSS.
> The pseudo-class function :is() (AKA “Matches Any”) takes a selector list and selects any element that can be selected by one of the selectors in that list.
> It can also be chained with other selectors such as :not() , :firstchild() etc.

想象你节省的所有行数！
这非常类似于嵌套与预处理器（例如SCSS）一起工作的方式。
伪类函数 :is() （别名 “匹配所有”）获取选择器列表，并选择任何可以被选择器选中的元素
它也可以链接其他选择器，例如 :not()，:firstchild() 等。

> #### :where()

#### :where()

> Just like :is(), :where() takes a selector list as its argument and selects any element that can be selected by one of the selectors in that list.
> Our code from before:

类似于 `:is()`，`where()` 将选择器列表作为其参数，并选择该列表中选择器之一可以选择的任何元素。
我们之前的代码：

```css
.main h1,
.main h2,
.main .heading, {
  line-height: 1.2;
}
.nav li,
.nav p {
  padding: 5px 10px;
}
```

> After using :where():

使用 `where()` 后：

```
.main :where(h1, h2, .heading){
  line-height: 1.2;
}
.nav :where(li, p) {
  padding: 5px 10px;
}
```

> “Wait, this looks exactly the same!”
> Yes, you’re right.

"等等，这看起来一样！"
没错

> #### So what’s the difference?

#### 区别是什么？

> **Specificity.**
> :is() takes the specificity of its most specific selector.
> :where() has a specificity of 0.
> It’s important to keep this small yet very important detail in mind when you’re using :is() and :where() in your code to avoid blocking yourself from applying CSS changes in other places.

**特异性**
`:is()` 采用其最具体的选择器的特异性。
`:where()` 的特异性为0。
当您在代码中使用 `:is()` 和 `:where()` 时，请记住这一小而非常重要的细节，这一点很重要，以避免阻止你自己在其他地方应用 CSS 更改。

> 译者注：它们之间的唯一区别是 `:where()` 不会增加整体选择器的特殊性（即某条 CSS 规则特殊性越高，它的样式越优先被采用）。
